return {
  'sindrets/diffview.nvim',
  dependencies = { 'nvim-lua/plenary.nvim' },
  cmd = { 'DiffviewOpen', 'DiffviewFileHistory' },
  keys = {
    { '<leader>gd', '<cmd>DiffviewOpen main<cr>',      desc = 'Diff working tree vs main' },
    { '<leader>gD', '<cmd>DiffviewOpen<cr>',            desc = 'Diff working tree vs HEAD' },
    { '<leader>gh', '<cmd>DiffviewFileHistory %<cr>',   desc = 'File history' },
    { '<leader>gH', '<cmd>DiffviewFileHistory<cr>',     desc = 'Repo history' },
    { '<leader>gx', '<cmd>DiffviewClose<cr>',           desc = 'Close diff view' },
    { '<leader>gm', '<cmd>DiffviewOpen main<cr>',       desc = 'Diff against main' },
  },
  opts = {
    use_icons = false,
    icons = {
      folder_closed = '+',
      folder_open = '-',
    },
    signs = {
      fold_closed = '>',
      fold_open = 'v',
      done = 'x',
    },
    keymaps = {
      view = {
        { 'n', 'q', '<cmd>DiffviewClose<cr>', { desc = 'Close diff view' } },
        { 'n', 'n', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next file' } },
        { 'n', 'p', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous file' } },
        { 'n', '<C-n>', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next file' } },
        { 'n', '<C-p>', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous file' } },
        { 'n', ']x', function() require('diffview.actions').next_conflict() end, { desc = 'Next conflict' } },
        { 'n', '[x', function() require('diffview.actions').prev_conflict() end, { desc = 'Previous conflict' } },
      },
      file_panel = {
        { 'n', 'q', '<cmd>DiffviewClose<cr>', { desc = 'Close diff view' } },
        { 'n', '<CR>', function() require('diffview.actions').goto_file_edit() end, { desc = 'Open file' } },
        { 'n', 'j', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next file' } },
        { 'n', 'k', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous file' } },
        { 'n', 'n', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next file' } },
        { 'n', 'p', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous file' } },
        { 'n', '<C-n>', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next file' } },
        { 'n', '<C-p>', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous file' } },
        { 'n', '<Tab>', function() require('diffview.actions').toggle_fold() end, { desc = 'Toggle fold' } },
      },
      file_history_panel = {
        { 'n', 'q', '<cmd>DiffviewClose<cr>', { desc = 'Close diff view' } },
        { 'n', '<CR>', function() require('diffview.actions').goto_file_edit() end, { desc = 'Open file' } },
        { 'n', 'j', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next entry' } },
        { 'n', 'k', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous entry' } },
        { 'n', 'n', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next entry' } },
        { 'n', 'p', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous entry' } },
        { 'n', '<C-n>', function() require('diffview.actions').select_next_entry() end, { desc = 'Open diff for next entry' } },
        { 'n', '<C-p>', function() require('diffview.actions').select_prev_entry() end, { desc = 'Open diff for previous entry' } },
        { 'n', '<Tab>', function() require('diffview.actions').toggle_fold() end, { desc = 'Toggle fold' } },
      },
    },
  },
}
